name: 22 Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
      
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: https://index.docker.io/v1/
        # Username used to log against the Docker registry
        username: ${{ secrets.dockerhub_username }}
        # Password or personal access token used to log against the Docker registry
        password:  ${{ secrets.dockerhub_password }}
        # Log out from the Docker registry at the end of a job
        logout: false
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
       push: true
       tags: index.docker.io/codingmoh/python-hello-world:latest
       file: ./Dockerfile
       
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2.2.5
      with:
        # Name of the Azure Web App
        app-name: fhtw-22-12
        # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: <publishData><publishProfile profileName="mo-style-streamlit - Web Deploy" publishMethod="MSDeploy" publishUrl="mo-style-streamlit.scm.azurewebsites.net:443" msdeploySite="mo-style-streamlit" userName="$mo-style-streamlit" userPWD="gvph5MdYmhPfWAFBwbQcuAPNympqm5uHxciXtwhmbcCAmimaKAT2R4jCGhjm" destinationAppUrl="https://mo-style-streamlit.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="mo-style-streamlit - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-db3-255.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="mo-style-streamlit\$mo-style-streamlit" userPWD="gvph5MdYmhPfWAFBwbQcuAPNympqm5uHxciXtwhmbcCAmimaKAT2R4jCGhjm" destinationAppUrl="https://mo-style-streamlit.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="mo-style-streamlit - Zip Deploy" publishMethod="ZipDeploy" publishUrl="mo-style-streamlit.scm.azurewebsites.net:443" userName="$mo-style-streamlit" userPWD="gvph5MdYmhPfWAFBwbQcuAPNympqm5uHxciXtwhmbcCAmimaKAT2R4jCGhjm" destinationAppUrl="https://mo-style-streamlit.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
        # Enter an existing Slot other than the Production slot
