name: Build and Deploy
on:
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: 'ubuntu'
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
       push: false
       tags: index.docker.io/codingmoh/python-hello-world:latest
       file: ./Dockerfile
